### ISSUE TITLE
integrating a blog into theme

### ISSUE THREAD

**Issue by shreyas42singh** [hadisinaee/avicenna#19]
Does the theme have to be a single page one?
How would I go about making separate pages for each of my projects (similar to ezhil).

**Comment by hadisinaee** [comment]
Hi @42shreyas ,

It is possible to do that. However, it was not merged into master. You can use the `develop` branch for that. There are some changes to be merged with the `master,` including the feature you mentioned.

If you have any problems, let me know.

**Comment by shreyas42singh** [comment]
I tried it, but any new "post" I make does not display the contents (header and logo come fine based on the sample in exampleSite). Is there something I'm doing wrong?
