### ISSUE TITLE
stylesheet - bad reference

### ISSUE THREAD

**Issue by cverluise** [hadisinaee/avicenna#22]
Hello,

it seems that the `baseUrl` is prefixed to css and js stylesheet files in index.html. 

For github depoyment at least, this causes css and js not to load properly. I removed the baseUrl by hand and now, this is alright. Would be nice to fix that in the theme.

```html
	<link rel="stylesheet" type="text/css" media="screen" href="<baseUrl>css/normalize.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<baseUrl>css/main.css"/>

	<script src="<baseUrl>js/feather.min.js"></script><script src="<baseUrl>js/main.js"></script>
```

Thanks in advance!

**Comment by KeAWang** [comment]
Any idea how to fix this within the Hugo theme?

**Comment by chixiangw** [comment]
I have exactly the same problem.

**Comment by hadisinaee** [comment]
@JeremyWng 

Thanks for reporting this issue. I am planning to refactor this project ASAP.
