### ISSUE TITLE
markdownify strips content

### ISSUE THREAD

**Issue by cheind** [hadisinaee/avicenna#27]
Hey, thanks for your theme!

 I tried using static pages like in 
https://github.com/hadisinaee/avicenna/tree/develop/exampleSite/content
However, for Hugo v0.74.3 this only renders the header but strips the content. I tracked down the issue to 
https://github.com/hadisinaee/avicenna/blob/8456dac8b56137266b9247ab213283387cc2e4d6/layouts/_default/single.html#L23
When I remove `markdownify` the content renders fine.

Note: I am new to Hugo so my conclusions might be quite possibly misleading.

**Comment by hadisinaee** [comment]
Thanks for reporting this issue. I am planning to refactor this project ASAP. I'll take a look at your problem/solution.

**Comment by cheind** [comment]
Thanks, I modified a couple of things as well: https://cheind.github.io/
One of the issues was that `href`s in the compiled page are not surrounded by quotes.

**Comment by hadisinaee** [comment]
The header idea is nice 👍🏼

**Comment by cheind** [comment]
Wanted to have somethin paper-like :)
