### ISSUE TITLE
space before trailing slash

### ISSUE THREAD

**Issue by linjiawu** [hadisinaee/avicenna#28]
Caught a bug in your template that makes rendering fail for my server:
in `themes/avicenna/layouts/partials/header.html` line 30, 
I changed 
30: 	<link rel="stylesheet" type="text/css" media="screen" href={{ "css/main.css" | absURL }}/>
to
30: 	<link rel="stylesheet" type="text/css" media="screen" href={{ "css/main.css" | absURL }} />
and it worked.

I guess it is not a problem for modern server, but it still takes me a while when I try to publish a personal website on my school's server.
c.f. https://stackoverflow.com/questions/462741/space-before-closing-slash

btw thanks for the template!

**Comment by hadisinaee** [comment]
@linjiawu 

Thank you! It's been a year that  I've not worked on this repo. I have a plan to refactor this and make new changes and adding new features.
