### ISSUE TITLE
need maintainer?

### ISSUE THREAD

**Issue by kaisugi** [hadisinaee/avicenna#30]
I'm very fond of your theme and truly hope this theme will be kept maintained! 
Since it looks like you have little time to review issues and pull requests, I would like to do the job instead.

If it's okay with you, you're welcome to transfer this repository to me (I have some experience in creating hugo themes e.g. https://github.com/HelloRusk/HugoTeX )

**Comment by hadisinaee** [comment]
Hi @HelloRusk 

Thanks for your interest! I recently refactored the code; however, there are some things to be fixed before pushing the changes. It's a little bit slow on my side, and I have to apologize for it.
