### ISSUE TITLE
Rewriting homepage info into contents/_index.md

### ISSUE THREAD

**Issue by paniash** [hadisinaee/avicenna#31]
Hi!

I think this setup could be made portable if the homepage info which is written to `config.toml` be written instead to `contents/_index.md` (which is usually the case for most themes). 

Or is there a possibility to make this optional? Thanks!

**Comment by hadisinaee** [comment]
Hi @paniash 

Thanks for your proposal. I recently refactored the code and made this change for flexibility both in terms of technical development and usage. I am looking for spare time to make the final changes and push the result.
