### ISSUE TITLE
Add other social icons

### ISSUE THREAD

**Issue by gerardchung** [hadisinaee/avicenna#33]
Hi Is it possible to have other social icons added? Like Researchgate and Google Scholar?

**Comment by hadisinaee** [comment]
@gerardchung 

Thanks for proposing that! I already added some extra social icons. It's in dev right now.

**Comment by gerardchung** [comment]
Thank you! :)

**Comment by iferres** [comment]
Hi @hadisinaee thank you for this theme! Is it possible to add ResearchGate and ORCID icons to the main page?

**Comment by hadisinaee** [comment]
Hi @iferres! Thanks for your suggestion. 

Yeah, sure! But I am busy these days. Also, I think I should find their proper icon and then add it.
